<?xml version="1.0"?>
<package format="3">
  <name>mur_driver</name>
  <version>0.0.1</version>

  <description>
    Bringup package for the MiR dual-UR5e mobile manipulator.
  </description>

  <maintainer email="todo@todo.com">fortis_dev</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>tf2_ros</exec_depend>

  <exec_depend>mir_driver</exec_depend>
  <exec_depend>dual_arm_driver</exec_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>