topics:
    - topic: "/cmd_vel"
      pub/sub: "pub"
    - topic: "/f_scan"
      pub/sub: "sub"
    - topic: "/b_scan"
      pub/sub: "sub"
    - topic: "/odom"
      pub/sub: "sub"
    - topic: "/tf"
      pub/sub: "sub"
    - topic: "/tf_static"
      pub/sub: "sub"
    - topic: "/MC/battery_percentage"
      pub/sub: "sub"
    - topic: "/robot_state"
      pub/sub: "sub"
