<?xml version="1.0"?>
<package format="3">
  <name>BrainCoRightHandURDF</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for BrainCoRightHandURDF</p>
    <p>This package contains fixed-joint Xacro and 3D models for BrainCoRightHandURDF robot</p>
  </description>
  <author>TODO</author>
  <maintainer email="TODO@email.com">TODO</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <architecture_independent/>
  </export>
</package>
