# Default initial positions for ur's ros2_control fake system
left_shoulder_pan_joint: -0.42
left_shoulder_lift_joint: -0.75
left_elbow_joint: -1.65
left_wrist_1_joint: -0.86
left_wrist_2_joint: 1.13
left_wrist_3_joint: -0.27
right_shoulder_pan_joint: -0.35
right_shoulder_lift_joint: 1.57
right_elbow_joint: 1.4
right_wrist_1_joint: -4.19
right_wrist_2_joint: -1.44
right_wrist_3_joint: 1.34